### ISSUE TITLE
Some question about convert doc to html

### ISSUE THREAD

**Issue by herryliq** [zrrrzzt/docker-unoconv-webservice#8]
I want convert .docx file to html format, and execute the follows cmd:
`curl --form file=@Kubernetes.docx http://localhost:8011/unoconv/html > myfile.html`

the result seems very well except the image that in the doc file can not convert .
Is it need some another config or other command about it?

**Comment by xverges** [comment]
May be related to https://ask.libreoffice.org/en/question/58576/headless-conversion-to-html-embeds-images-instead-of-creating-separate-files/?answer=141703#post-id-141703

**Comment by kchapple** [comment]
@zrrrzzt This appears to be an issue because the service only returns the converted HTML file, and not the linked images. In an HTML document, the images are external links to png files that are generated by unoconv, but those image files are not returned by the service, only the HTML document. Any idea if this is possible to fix?

**Comment by zrrrzzt** [comment]
You are right. This service only returns 1 file, even if there are several created by unoconv.
It might be possible to fix but I'm probably not going to do it. I'm not using this service myself anymore.
PRs are welcome though :-)

**Comment by zrrrzzt** [comment]
Just added support for multiple files in this service https://github.com/Alheimsins/micro-office-converter @kchapple 
It is kind of the same but less tested :-)

**Comment by kchapple** [comment]
Than you @zrrrzzt I will investigate the options. I appreciate your response!
